version: '3.6'
services:
  redis-cache:
    image: redis:alpine
    container_name: redis-cache

  api:
    container_name: checkin-api
    depends_on:
      - redis-cache
    env_file:
      - backend/.env.dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - './backend:/backend'

